### PR TITLE
Update to 3.5.1

### PR DESCRIPTION
**Pull request by barsa-net**
TeamSpeak now provides alpine-compatible binaries thus it's possible to use last official alpine release (3.8)
"MANTAINER" instruction is deprecated in favor of "LABEL maintainer"
Removed mysql-client as it should not affect TSDNS capabilities

### CODE REVIEW

**Comment by solidnerd** [comment]
Hey, 

thanks for your pull request. I would really appreciate that you splitt your commits. For each change. So it would be easier to revert or cherry-pick.

I won't like to change the base image only in terms of size. Why I don't see to use alpine here is that we use a dns service in the container. 
Here are some example caveats: 
https://github.com/gliderlabs/docker-alpine/blob/master/docs/caveats.md#dns

If you did the update into separate commits. I would like to merge everything except changing the base image.

**Comment by solidnerd** [comment]
A better alternative would be to use alpine with glibc or using debian:stretch-slim as base image.

**Comment by barsa-net** [comment]
<s>I thought the container would be tsdns only, that's the reason of my change to alpine:3.8, I can surely revert that change to your solidnerd/alpine-glibc:2.23-r3</s>
Edit: Ignore this reply, I completely misunderstood what you meant when I wrote it.

**Comment by barsa-net** [comment]
Let me know if that was what you had in mind, I'm not quite fluent yet in git

**Pull request closed without merging**
